cloud:
  version: 5
  product: SUSE OpenStack Cloud

admin_node:
  os:
    name: SUSE Linux Enterprise Server 11
    version: 11
    patchlevel: 3

  ip: CAN'T BE BLANK # IP or FQDN allowed
  ssh:
    user: root
    password:
    port: 22

  api:
    user: crowbar
    password: CAN'T BE BLANK
    port: 3000
    ssl: false

control_node:
  ssh:
    user: root
    password:
    port: 22

timeout:
  ssh: 5
  http: 5

