cloud:
  version: 5
  product: SUSE OpenStack Cloud

admin_node:
  os:
    name: SUSE Linux Enterprise Server 11
    version: 11
    patchlevel: 3

  api:
    url: localhost
    port: 3000
    ssl: true

timeout:
  ssh: 5
  http: 5

