# Use this file for your configuration data.
# This file is being merged with with the default.yml config; sections
# entered here will overwrite the defaults
#
# Example:
#
# admin_node:
#   ip: 192.168.175.10
#   ssh:
#     user: root
#     password: linux
#     port: 22
#   api:
#     user: crowbar
#     password: linux
#     port: 3000
#     ssl: false
