---
admin_node:
  remote:
    ip:
    ssh:
      user: root
      password:
      port: 22

    api:
      user: crowbar
      password:
      port: 3000
      ssl: false

gateway:
  ip:
  user:
  password:

timeout:
  ssh: 2
  http: 1
