---
admin_node:
  remote:
    ip: 10.162.24.10
    ssh:
      user: root
      password: linux
      port: 22

    api:
      user: crowbar
      password: 088435ca9456bc954677d88d08b8020f
      port: 3000
      ssl: false

gateway:
  ip:
  user:
  password:

timeout:
  ssh: 2
  http: 1
