---
admin_node:
  remote:
    ip: CAN'T BE BLANK
    ssh:
      user: root
      password:
      port: 22

    api:
      user: crowbar
      password: CAN'T BE BLANK
      port: 3000
      ssl: false

gateway:
  ip:
  user:
  password:

timeout:
  ssh: 2
  http: 1

